export const categoryList = [
    {
        id:1,
        path:'/business',
        title:'Business'
    },
    {
        id:2,
        path:'/entertainment',
        title:'Entertainment'
    },
    {
        id:3,
        path:'/general',
        title:'General'
    },
    {
        id:4,
        path:'/health',
        title:'Health'
    },
    {
        id:5,
        path:'/science',
        title:'Science'
    },
    {
        id:6,
        path:'/sports',
        title:'Sports'
    },
    {
        id:6,
        path:'/technology',
        title:'Technology'
    }
]